const countries = [
  { name: "Afghanistan", flag: "https://flagcdn.com/w40/af.png" },
  { name: "Albania", flag: "https://flagcdn.com/w40/al.png" },
  { name: "Algeria", flag: "https://flagcdn.com/w40/dz.png" },
  { name: "Andorra", flag: "https://flagcdn.com/w40/ad.png" },
  { name: "Angola", flag: "https://flagcdn.com/w40/ao.png" },
  { name: "Antigua and Barbuda", flag: "https://flagcdn.com/w40/ag.png" },
  { name: "Argentina", flag: "https://flagcdn.com/w40/ar.png" },
  { name: "Armenia", flag: "https://flagcdn.com/w40/am.png" },
  { name: "Australia", flag: "https://flagcdn.com/w40/au.png" },
  { name: "Austria", flag: "https://flagcdn.com/w40/at.png" },
  { name: "Azerbaijan", flag: "https://flagcdn.com/w40/az.png" },
  { name: "Bahamas", flag: "https://flagcdn.com/w40/bs.png" },
  { name: "Bahrain", flag: "https://flagcdn.com/w40/bh.png" },
  { name: "Bangladesh", flag: "https://flagcdn.com/w40/bd.png" },
  { name: "Barbados", flag: "https://flagcdn.com/w40/bb.png" },
  { name: "Belarus", flag: "https://flagcdn.com/w40/by.png" },
  { name: "Belgium", flag: "https://flagcdn.com/w40/be.png" },
  { name: "Belize", flag: "https://flagcdn.com/w40/bz.png" },
  { name: "Benin", flag: "https://flagcdn.com/w40/bj.png" },
  { name: "Bhutan", flag: "https://flagcdn.com/w40/bt.png" },
  { name: "Bolivia", flag: "https://flagcdn.com/w40/bo.png" },
  { name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w40/ba.png" },
  { name: "Botswana", flag: "https://flagcdn.com/w40/bw.png" },
  { name: "Brazil", flag: "https://flagcdn.com/w40/br.png" },
  { name: "Brunei", flag: "https://flagcdn.com/w40/bn.png" },
  { name: "Bulgaria", flag: "https://flagcdn.com/w40/bg.png" },
  { name: "Burkina Faso", flag: "https://flagcdn.com/w40/bf.png" },
  { name: "Burundi", flag: "https://flagcdn.com/w40/bi.png" },
  { name: "Cabo Verde", flag: "https://flagcdn.com/w40/cv.png" },
  { name: "Cambodia", flag: "https://flagcdn.com/w40/kh.png" },
  { name: "Cameroon", flag: "https://flagcdn.com/w40/cm.png" },
  { name: "Canada", flag: "https://flagcdn.com/w40/ca.png" },
  { name: "Central African Republic", flag: "https://flagcdn.com/w40/cf.png" },
  { name: "Chad", flag: "https://flagcdn.com/w40/td.png" },
  { name: "Chile", flag: "https://flagcdn.com/w40/cl.png" },
  { name: "China", flag: "https://flagcdn.com/w40/cn.png" },
  { name: "Colombia", flag: "https://flagcdn.com/w40/co.png" },
  { name: "Comoros", flag: "https://flagcdn.com/w40/km.png" },
  { name: "Congo (Congo-Brazzaville)", flag: "https://flagcdn.com/w40/cg.png" },
  { name: "Costa Rica", flag: "https://flagcdn.com/w40/cr.png" },
  { name: "Croatia", flag: "https://flagcdn.com/w40/hr.png" },
  { name: "Cuba", flag: "https://flagcdn.com/w40/cu.png" },
  { name: "Cyprus", flag: "https://flagcdn.com/w40/cy.png" },
  { name: "Czech Republic", flag: "https://flagcdn.com/w40/cz.png" },
  { name: "Democratic Republic of the Congo", flag: "https://flagcdn.com/w40/cd.png" },
  { name: "Denmark", flag: "https://flagcdn.com/w40/dk.png" },
  { name: "Djibouti", flag: "https://flagcdn.com/w40/dj.png" },
  { name: "Dominica", flag: "https://flagcdn.com/w40/dm.png" },
  { name: "Dominican Republic", flag: "https://flagcdn.com/w40/do.png" },
  { name: "Ecuador", flag: "https://flagcdn.com/w40/ec.png" },
  { name: "Egypt", flag: "https://flagcdn.com/w40/eg.png" },
  { name: "El Salvador", flag: "https://flagcdn.com/w40/sv.png" },
  { name: "Equatorial Guinea", flag: "https://flagcdn.com/w40/gq.png" },
  { name: "Eritrea", flag: "https://flagcdn.com/w40/er.png" },
  { name: "Estonia", flag: "https://flagcdn.com/w40/ee.png" },
  { name: "Eswatini", flag: "https://flagcdn.com/w40/sz.png" },
  { name: "Ethiopia", flag: "https://flagcdn.com/w40/et.png" },
  { name: "Fiji", flag: "https://flagcdn.com/w40/fj.png" },
  { name: "Finland", flag: "https://flagcdn.com/w40/fi.png" },
  { name: "France", flag: "https://flagcdn.com/w40/fr.png" },
  { name: "Gabon", flag: "https://flagcdn.com/w40/ga.png" },
  { name: "Gambia", flag: "https://flagcdn.com/w40/gm.png" },
  { name: "Georgia", flag: "https://flagcdn.com/w40/ge.png" },
  { name: "Germany", flag: "https://flagcdn.com/w40/de.png" },
  { name: "Ghana", flag: "https://flagcdn.com/w40/gh.png" },
  { name: "Greece", flag: "https://flagcdn.com/w40/gr.png" },
  { name: "Grenada", flag: "https://flagcdn.com/w40/gd.png" },
  { name: "Guatemala", flag: "https://flagcdn.com/w40/gt.png" },
  { name: "Guinea", flag: "https://flagcdn.com/w40/gn.png" },
  { name: "Guinea-Bissau", flag: "https://flagcdn.com/w40/gw.png" },
  { name: "Guyana", flag: "https://flagcdn.com/w40/gy.png" },
  { name: "Haiti", flag: "https://flagcdn.com/w40/ht.png" },
  { name: "Honduras", flag: "https://flagcdn.com/w40/hn.png" },
  { name: "Hungary", flag: "https://flagcdn.com/w40/hu.png" },
  { name: "Iceland", flag: "https://flagcdn.com/w40/is.png" },
  { name: "India", flag: "https://flagcdn.com/w40/in.png" },
  { name: "Indonesia", flag: "https://flagcdn.com/w40/id.png" },
  { name: "Iran", flag: "https://flagcdn.com/w40/ir.png" },
  { name: "Iraq", flag: "https://flagcdn.com/w40/iq.png" },
  { name: "Ireland", flag: "https://flagcdn.com/w40/ie.png" },
  { name: "Israel", flag: "https://flagcdn.com/w40/il.png" },
  { name: "Italy", flag: "https://flagcdn.com/w40/it.png" },
  { name: "Ivory Coast", flag: "https://flagcdn.com/w40/ci.png" },
  { name: "Jamaica", flag: "https://flagcdn.com/w40/jm.png" },
  { name: "Japan", flag: "https://flagcdn.com/w40/jp.png" },
  { name: "Jordan", flag: "https://flagcdn.com/w40/jo.png" },
  { name: "Kazakhstan", flag: "https://flagcdn.com/w40/kz.png" },
  { name: "Kenya", flag: "https://flagcdn.com/w40/ke.png" },
  { name: "Kiribati", flag: "https://flagcdn.com/w40/ki.png" },
  { name: "Kuwait", flag: "https://flagcdn.com/w40/kw.png" },
  { name: "Kyrgyzstan", flag: "https://flagcdn.com/w40/kg.png" },
  { name: "Laos", flag: "https://flagcdn.com/w40/la.png" },
  { name: "Latvia", flag: "https://flagcdn.com/w40/lv.png" },
  { name: "Lebanon", flag: "https://flagcdn.com/w40/lb.png" },
  { name: "Lesotho", flag: "https://flagcdn.com/w40/ls.png" },
  { name: "Liberia", flag: "https://flagcdn.com/w40/lr.png" },
  { name: "Libya", flag: "https://flagcdn.com/w40/ly.png" },
  { name: "Liechtenstein", flag: "https://flagcdn.com/w40/li.png" },
  { name: "Lithuania", flag: "https://flagcdn.com/w40/lt.png" },
  { name: "Luxembourg", flag: "https://flagcdn.com/w40/lu.png" },
  { name: "Madagascar", flag: "https://flagcdn.com/w40/mg.png" },
  { name: "Malawi", flag: "https://flagcdn.com/w40/mw.png" },
  { name: "Malaysia", flag: "https://flagcdn.com/w40/my.png" },
  { name: "Maldives", flag: "https://flagcdn.com/w40/mv.png" },
  { name: "Mali", flag: "https://flagcdn.com/w40/ml.png" },
  { name: "Malta", flag: "https://flagcdn.com/w40/mt.png" },
  { name: "Marshall Islands", flag: "https://flagcdn.com/w40/mh.png" },
  { name: "Mauritania", flag: "https://flagcdn.com/w40/mr.png" },
  { name: "Mauritius", flag: "https://flagcdn.com/w40/mu.png" },
  { name: "Mexico", flag: "https://flagcdn.com/w40/mx.png" },
  { name: "Micronesia", flag: "https://flagcdn.com/w40/fm.png" },
  { name: "Moldova", flag: "https://flagcdn.com/w40/md.png" },
  { name: "Monaco", flag: "https://flagcdn.com/w40/mc.png" },
  { name: "Mongolia", flag: "https://flagcdn.com/w40/mn.png" },
  { name: "Montenegro", flag: "https://flagcdn.com/w40/me.png" },
  { name: "Morocco", flag: "https://flagcdn.com/w40/ma.png" },
  { name: "Mozambique", flag: "https://flagcdn.com/w40/mz.png" },
  { name: "Myanmar", flag: "https://flagcdn.com/w40/mm.png" },
  { name: "Namibia", flag: "https://flagcdn.com/w40/na.png" },
  { name: "Nauru", flag: "https://flagcdn.com/w40/nr.png" },
  { name: "Nepal", flag: "https://flagcdn.com/w40/np.png" },
  { name: "Netherlands", flag: "https://flagcdn.com/w40/nl.png" },
  { name: "New Zealand", flag: "https://flagcdn.com/w40/nz.png" },
  { name: "Nicaragua", flag: "https://flagcdn.com/w40/ni.png" },
  { name: "Niger", flag: "https://flagcdn.com/w40/ne.png" },
  { name: "Nigeria", flag: "https://flagcdn.com/w40/ng.png" },
  { name: "North Korea", flag: "https://flagcdn.com/w40/kp.png" },
  { name: "North Macedonia", flag: "https://flagcdn.com/w40/mk.png" },
  { name: "Norway", flag: "https://flagcdn.com/w40/no.png" },
  { name: "Oman", flag: "https://flagcdn.com/w40/om.png" },
  { name: "Pakistan", flag: "https://flagcdn.com/w40/pk.png" },
  { name: "Palau", flag: "https://flagcdn.com/w40/pw.png" },
  { name: "Palestine State", flag: "https://flagcdn.com/w40/ps.png" },
  { name: "Panama", flag: "https://flagcdn.com/w40/pa.png" },
  { name: "Papua New Guinea", flag: "https://flagcdn.com/w40/pg.png" },
  { name: "Paraguay", flag: "https://flagcdn.com/w40/py.png" },
  { name: "Peru", flag: "https://flagcdn.com/w40/pe.png" },
  { name: "Philippines", flag: "https://flagcdn.com/w40/ph.png" },
  { name: "Poland", flag: "https://flagcdn.com/w40/pl.png" },
  { name: "Portugal", flag: "https://flagcdn.com/w40/pt.png" },
  { name: "Qatar", flag: "https://flagcdn.com/w40/qa.png" },
  { name: "Romania", flag: "https://flagcdn.com/w40/ro.png" },
  { name: "Russia", flag: "https://flagcdn.com/w40/ru.png" },
  { name: "Rwanda", flag: "https://flagcdn.com/w40/rw.png" },
  { name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/w40/kn.png" },
  { name: "Saint Lucia", flag: "https://flagcdn.com/w40/lc.png" },
  { name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/w40/vc.png" },
  { name: "Samoa", flag: "https://flagcdn.com/w40/ws.png" },
  { name: "San Marino", flag: "https://flagcdn.com/w40/sm.png" },
  { name: "Sao Tome and Principe", flag: "https://flagcdn.com/w40/st.png" },
  { name: "Saudi Arabia", flag: "https://flagcdn.com/w40/sa.png" },
  { name: "Senegal", flag: "https://flagcdn.com/w40/sn.png" },
  { name: "Serbia", flag: "https://flagcdn.com/w40/rs.png" },
  { name: "Seychelles", flag: "https://flagcdn.com/w40/sc.png" },
  { name: "Sierra Leone", flag: "https://flagcdn.com/w40/sl.png" },
  { name: "Singapore", flag: "https://flagcdn.com/w40/sg.png" },
  { name: "Slovakia", flag: "https://flagcdn.com/w40/sk.png" },
  { name: "Slovenia", flag: "https://flagcdn.com/w40/si.png" },
  { name: "Solomon Islands", flag: "https://flagcdn.com/w40/sb.png" },
  { name: "Somalia", flag: "https://flagcdn.com/w40/so.png" },
  { name: "South Africa", flag: "https://flagcdn.com/w40/za.png" },
  { name: "South Korea", flag: "https://flagcdn.com/w40/kr.png" },
  { name: "South Sudan", flag: "https://flagcdn.com/w40/ss.png" },
  { name: "Spain", flag: "https://flagcdn.com/w40/es.png" },
  { name: "Sri Lanka", flag: "https://flagcdn.com/w40/lk.png" },
  { name: "Sudan", flag: "https://flagcdn.com/w40/sd.png" },
  { name: "Suriname", flag: "https://flagcdn.com/w40/sr.png" },
  { name: "Sweden", flag: "https://flagcdn.com/w40/se.png" },
  { name: "Switzerland", flag: "https://flagcdn.com/w40/ch.png" },
  { name: "Syria", flag: "https://flagcdn.com/w40/sy.png" },
  { name: "Taiwan", flag: "https://flagcdn.com/w40/tw.png" },
  { name: "Tajikistan", flag: "https://flagcdn.com/w40/tj.png" },
  { name: "Tanzania", flag: "https://flagcdn.com/w40/tz.png" },
  { name: "Thailand", flag: "https://flagcdn.com/w40/th.png" },
  { name: "Timor-Leste", flag: "https://flagcdn.com/w40/tl.png" },
  { name: "Togo", flag: "https://flagcdn.com/w40/tg.png" },
  { name: "Tonga", flag: "https://flagcdn.com/w40/to.png" },
  { name: "Trinidad and Tobago", flag: "https://flagcdn.com/w40/tt.png" },
  { name: "Tunisia", flag: "https://flagcdn.com/w40/tn.png" },
  { name: "Turkey", flag: "https://flagcdn.com/w40/tr.png" },
  { name: "Turkmenistan", flag: "https://flagcdn.com/w40/tm.png" },
  { name: "Tuvalu", flag: "https://flagcdn.com/w40/tv.png" },
  { name: "Uganda", flag: "https://flagcdn.com/w40/ug.png" },
  { name: "Ukraine", flag: "https://flagcdn.com/w40/ua.png" },
  { name: "United Arab Emirates", flag: "https://flagcdn.com/w40/ae.png" },
  { name: "United Kingdom", flag: "https://flagcdn.com/w40/gb.png" },
  { name: "United States", flag: "https://flagcdn.com/w40/us.png" },
  { name: "Uruguay", flag: "https://flagcdn.com/w40/uy.png" },
  { name: "Uzbekistan", flag: "https://flagcdn.com/w40/uz.png" },
  { name: "Vanuatu", flag: "https://flagcdn.com/w40/vu.png" },
  { name: "Vatican City", flag: "https://flagcdn.com/w40/va.png" },
  { name: "Venezuela", flag: "https://flagcdn.com/w40/ve.png" },
  { name: "Vietnam", flag: "https://flagcdn.com/w40/vn.png" },
  { name: "Yemen", flag: "https://flagcdn.com/w40/ye.png" },
  { name: "Zambia", flag: "https://flagcdn.com/w40/zm.png" },
  { name: "Zimbabwe", flag: "https://flagcdn.com/w40/zw.png" },
];